export const ACTIONS = {
  SET_LOADING: "SET_LOADING",
  SET_WALLET_ADDRESS: "SET_WALLET_ADDRESS",
  IS_METAMASK_PRESENT: "IS_METAMASK_PRESENT",
  SET_DISCORD_NAME: "SET_DISCORD_NAME",
  SET_TWITTER_NAME: "SET_TWITTER_NAME",
};
